apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ai-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DATA_SERVICE_URL
              value: "http://data-service:8000/metrics"
            - name: DEEPSEEK_API_KEY
              value: "sk-d14d57adef31432f888f312aa56c51ef"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer